# 1. canonical peptide classification

In [1]:
from pepbenchmark.model.plm_model import build_plm_model
from pepbenchmark.dataset_manager.single_dataset import SinglePeptideDatasetManager

dataset = SinglePeptideDatasetManager(
    "ace_inhibitory",
    official_feature_names=["fasta", "label"],
    dataset_dir="../../PepBenchData/PepBenchData-50",
)
runner = build_plm_model(
    model_type="plm",      
    dataset=dataset,
    task_type="binary_classification",
    model_name="facebook/esm2_t30_150M_UR50D",    
    epochs=50,
    batch_size=64,
    learning_rate=5e-5,
    weight_decay=0,
    early_stopping_patience=5,
)

multi_results = runner.run_multi(
    run_seeds=[42, 43, 44, 45, 46],
    fold_seeds=[0, 1, 2, 3, 4],
    split_type="hybrid_split",   
)
print(multi_results.to_dataframe())
summary = multi_results.get_summary_stats()
print(summary["test_roc-auc"])

2026-03-28 11:38:14 | INFO     | pepbenchmark | Loaded official feature: fasta
2026-03-28 11:38:14 | INFO     | pepbenchmark | Loaded official feature: label
2026-03-28 11:38:14 | INFO     | pepbenchmark | [RUN_MULTI] running seed=42, fold=0
2026-03-28 11:38:14 | INFO     | pepbenchmark | [RUN] model=facebook/esm2_t30_150M_UR50D | seed=42, fold=0, split=hybrid_split
2026-03-28 11:38:14 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====0=== successfully

Some weights of EsmForSequenceClassification were not initialized from the model checkpoint at facebook/esm2_t30_150M_UR50D and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

dict_keys(['fasta', 'label'])
dict_keys(['fasta', 'label'])
2026-03-28 11:38:18 | INFO     | pepbenchmark | [TRAIN] model=facebook/esm2_t30_150M_UR50D, split=hybrid_split, fold=0, seed=42

2026-03-28 11:40:51 | INFO     | pepbenchmark | [TRAIN DONE] facebook/esm2_t30_150M_UR50D in 153.00s
2026-03-28 11:40:55 | INFO     | pepbenchmark | [SAVE MODEL] saved to ./results/ace_inhibitory/facebook_esm2_t30_150M_UR50D/hybrid_split/fold_0_seed_42/model

2026-03-28 11:40:58 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.8186638388123012, 'balanced-accuracy': 0.8176355820701837, 'precision': 0.8153745072273325, 'recall': 0.8424983027834352, 'specificity': np.float64(0.7927728613569321), 'f1': 0.8287145242070116, 'micro-f1': 0.8186638388123012, 'macro-f1': 0.8180373221861195, 'weighted-f1': 0.8184789031816813, 'mcc': 0.6365686415343469, 'kappa': 0.6361841674807718, 'g-mean': np.float64(0.8172574809605495), 'roc-auc': 0.9074045703689018, 'avg-roc-auc': 0.9074045703689018, 'pr-auc': 0.9181820886753408, 'brier-score': 0.1296823219100533, 'log-loss': 0.4118982036942362}

2026-03-28 11:40:59 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.7223796033994334, 'balanced-accuracy': 0.718297998811175, 'precision': 0.6580645161290323, 'recall': 0.6938775510204082, 'specificity': np.float64(0.7427184466019418), 'f1': 0.6754966887417219, 'micro-f1': 0.7223796033994334, 'macro-f1': 0.7164612156579897, 'weighted-f1': 0.7233079779471109, 'mcc': 0.4336841832753821, 'kappa': 0.43321973917032575, 'g-mean': np.float64(0.7178827598054136), 'roc-auc': 0.7877286837064923, 'avg-roc-auc': 0.7877286837064923, 'pr-auc': 0.7415848944457246, 'brier-score': 0.18725189847819204, 'log-loss': 0.5538568421898554}

2026-03-28 11:40:59 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.7352112676056338, 'balanced-accuracy': 0.7376460017969453, 'precision': 0.6836158192090396, 'recall': 0.7610062893081762, 'specificity': np.float64(0.7142857142857143), 'f1': 0.7202380952380952, 'micro-f1': 0.7352112676056338, 'macro-f1': 0.7344505984211867, 'weighted-f1': 0.7359319015698468, 'mcc': 0.4727052994968789, 'kappa': 0.4702670095564657, 'g-mean': np.float64(0.737276014077775), 'roc-auc': 0.7990309331279681, 'avg-roc-auc': 0.7990309331279681, 'pr-auc': 0.7568640063409626, 'brier-score': 0.18645361220794196, 'log-loss': 0.5555920727823774}
2026-03-28 11:40:59 | INFO     | pepbenchmark | [RUN_MULTI] running seed=43, fold=1
2026-03-28 11:40:59 | INFO     | pepbenchmark | [RUN] model=facebook/esm2_t30_150M_UR50D | seed=43, fold=1, split=hybrid_split
2026-03-28 11:40:59 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====1=== successfully

Some weights of EsmForSequenceClassification were not initialized from the model checkpoint at facebook/esm2_t30_150M_UR50D and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

dict_keys(['fasta', 'label'])
dict_keys(['fasta', 'label'])
2026-03-28 11:41:02 | INFO     | pepbenchmark | [TRAIN] model=facebook/esm2_t30_150M_UR50D, split=hybrid_split, fold=1, seed=43

2026-03-28 11:43:32 | INFO     | pepbenchmark | [TRAIN DONE] facebook/esm2_t30_150M_UR50D in 149.98s
2026-03-28 11:43:36 | INFO     | pepbenchmark | [SAVE MODEL] saved to ./results/ace_inhibitory/facebook_esm2_t30_150M_UR50D/hybrid_split/fold_1_seed_43/model

2026-03-28 11:43:38 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.8356309650053022, 'balanced-accuracy': 0.8376463700234192, 'precision': 0.888715953307393, 'recall': 0.7800546448087432, 'specificity': np.float64(0.8952380952380953), 'f1': 0.8308475809385231, 'micro-f1': 0.8356309650053022, 'macro-f1': 0.8354994178326167, 'weighted-f1': 0.8353366282064183, 'mcc': 0.6777253537639244, 'kappa': 0.672311786373246, 'g-mean': np.float64(0.835664187577886), 'roc-auc': 0.9124887407674293, 'avg-roc-auc': 0.9124887407674293, 'pr-auc': 0.9177142757587116, 'brier-score': 0.12401131602333901, 'log-loss': 0.39964581799861737}

2026-03-28 11:43:39 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.71671388101983, 'balanced-accuracy': 0.6981345485541932, 'precision': 0.7107438016528925, 'recall': 0.5695364238410596, 'specificity': np.float64(0.8267326732673267), 'f1': 0.6323529411764706, 'micro-f1': 0.71671388101983, 'macro-f1': 0.7009690973163458, 'weighted-f1': 0.7108824796481692, 'mcc': 0.4130643232087509, 'kappa': 0.4064633285132999, 'g-mean': np.float64(0.686188290635473), 'roc-auc': 0.7869647891941512, 'avg-roc-auc': 0.7869647891941512, 'pr-auc': 0.7358550136008761, 'brier-score': 0.1856371834143933, 'log-loss': 0.5522980662910719}

2026-03-28 11:43:39 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.7070422535211267, 'balanced-accuracy': 0.6980111096922488, 'precision': 0.7307692307692307, 'recall': 0.5792682926829268, 'specificity': np.float64(0.8167539267015707), 'f1': 0.6462585034013606, 'micro-f1': 0.7070422535211267, 'macro-f1': 0.6981292517006803, 'weighted-f1': 0.7020743508671075, 'mcc': 0.40982195973685154, 'kappa': 0.4019115502996923, 'g-mean': np.float64(0.6878369375531495), 'roc-auc': 0.8006321031796706, 'avg-roc-auc': 0.8006321031796706, 'pr-auc': 0.7782447187150433, 'brier-score': 0.186775940976679, 'log-loss': 0.5486242776407548}
2026-03-28 11:43:40 | INFO     | pepbenchmark | [RUN_MULTI] running seed=44, fold=2
2026-03-28 11:43:40 | INFO     | pepbenchmark | [RUN] model=facebook/esm2_t30_150M_UR50D | seed=44, fold=2, split=hybrid_split
2026-03-28 11:43:40 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====2=== successfully

Some weights of EsmForSequenceClassification were not initialized from the model checkpoint at facebook/esm2_t30_150M_UR50D and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

dict_keys(['fasta', 'label'])
dict_keys(['fasta', 'label'])
2026-03-28 11:43:43 | INFO     | pepbenchmark | [TRAIN] model=facebook/esm2_t30_150M_UR50D, split=hybrid_split, fold=2, seed=44

2026-03-28 11:46:16 | INFO     | pepbenchmark | [TRAIN DONE] facebook/esm2_t30_150M_UR50D in 153.48s
2026-03-28 11:46:20 | INFO     | pepbenchmark | [SAVE MODEL] saved to ./results/ace_inhibitory/facebook_esm2_t30_150M_UR50D/hybrid_split/fold_2_seed_44/model

2026-03-28 11:46:23 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.8692117355956168, 'balanced-accuracy': 0.8697932141838862, 'precision': 0.8911319394376351, 'recall': 0.8494845360824742, 'specificity': np.float64(0.8901018922852983), 'f1': 0.8698099929627023, 'micro-f1': 0.8692117355956168, 'macro-f1': 0.8692089737540785, 'weighted-f1': 0.869226182151356, 'mcc': 0.7394229661160091, 'kappa': 0.7385689966252464, 'g-mean': np.float64(0.8695560896423583), 'roc-auc': 0.9475182200613256, 'avg-roc-auc': 0.9475182200613256, 'pr-auc': 0.955577609863572, 'brier-score': 0.10086375171736538, 'log-loss': 0.33596980087572714}

2026-03-28 11:46:23 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.6855524079320113, 'balanced-accuracy': 0.6805394244418634, 'precision': 0.6802721088435374, 'recall': 0.6097560975609756, 'specificity': np.float64(0.7513227513227513), 'f1': 0.6430868167202572, 'micro-f1': 0.6855524079320113, 'macro-f1': 0.6810370792462046, 'weighted-f1': 0.6837247748925182, 'mcc': 0.36531087233003245, 'kappa': 0.3635713937661409, 'g-mean': np.float64(0.6768483056456123), 'roc-auc': 0.7526455026455026, 'avg-roc-auc': 0.7526455026455026, 'pr-auc': 0.72098895298948, 'brier-score': 0.20535196404834594, 'log-loss': 0.6079668032548711}

2026-03-28 11:46:23 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.7098591549295775, 'balanced-accuracy': 0.6994391025641026, 'precision': 0.7142857142857143, 'recall': 0.59375, 'specificity': np.float64(0.8051282051282052), 'f1': 0.6484641638225256, 'micro-f1': 0.7098591549295775, 'macro-f1': 0.7007308828704955, 'weighted-f1': 0.7058839396780417, 'mcc': 0.41002968185161914, 'kappa': 0.40501179725002034, 'g-mean': np.float64(0.6914078910418017), 'roc-auc': 0.7948397435897435, 'avg-roc-auc': 0.7948397435897435, 'pr-auc': 0.7730724950077164, 'brier-score': 0.18407156363234847, 'log-loss': 0.5449722592689884}
2026-03-28 11:46:23 | INFO     | pepbenchmark | [RUN_MULTI] running seed=45, fold=3
2026-03-28 11:46:23 | INFO     | pepbenchmark | [RUN] model=facebook/esm2_t30_150M_UR50D | seed=45, fold=3, split=hybrid_split
2026-03-28 11:46:23 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====3=== successfully

Some weights of EsmForSequenceClassification were not initialized from the model checkpoint at facebook/esm2_t30_150M_UR50D and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

dict_keys(['fasta', 'label'])
dict_keys(['fasta', 'label'])
2026-03-28 11:46:26 | INFO     | pepbenchmark | [TRAIN] model=facebook/esm2_t30_150M_UR50D, split=hybrid_split, fold=3, seed=45

2026-03-28 11:48:57 | INFO     | pepbenchmark | [TRAIN DONE] facebook/esm2_t30_150M_UR50D in 150.60s
2026-03-28 11:49:02 | INFO     | pepbenchmark | [SAVE MODEL] saved to ./results/ace_inhibitory/facebook_esm2_t30_150M_UR50D/hybrid_split/fold_3_seed_45/model

2026-03-28 11:49:04 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.8137150936726758, 'balanced-accuracy': 0.8129877544887687, 'precision': 0.8173333333333334, 'recall': 0.8289384719405003, 'specificity': np.float64(0.797037037037037), 'f1': 0.8230949983215844, 'micro-f1': 0.8137150936726758, 'macro-f1': 0.8131899030428378, 'weighted-f1': 0.8136415669844985, 'mcc': 0.6264698768058021, 'kappa': 0.6264004504595936, 'g-mean': np.float64(0.8128312638927376), 'roc-auc': 0.893100443242431, 'avg-roc-auc': 0.893100443242431, 'pr-auc': 0.905029981924725, 'brier-score': 0.1364261891615973, 'log-loss': 0.428922924111606}

2026-03-28 11:49:05 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.6968838526912181, 'balanced-accuracy': 0.7022983950861899, 'precision': 0.6136363636363636, 'recall': 0.7346938775510204, 'specificity': np.float64(0.6699029126213593), 'f1': 0.6687306501547987, 'micro-f1': 0.6968838526912181, 'macro-f1': 0.6946786410042923, 'weighted-f1': 0.6990155573219131, 'mcc': 0.39890707911505485, 'kappa': 0.3934805299076676, 'g-mean': np.float64(0.7015508309855452), 'roc-auc': 0.7902714483851793, 'avg-roc-auc': 0.7902714483851793, 'pr-auc': 0.7147301842719296, 'brier-score': 0.18415248984858676, 'log-loss': 0.5464747086873867}

2026-03-28 11:49:05 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.7126760563380282, 'balanced-accuracy': 0.7118520675596971, 'precision': 0.6545454545454545, 'recall': 0.7058823529411765, 'specificity': np.float64(0.7178217821782178), 'f1': 0.6792452830188679, 'micro-f1': 0.7126760563380282, 'macro-f1': 0.7095206006931074, 'weighted-f1': 0.7136994473580024, 'mcc': 0.4206930428996061, 'kappa': 0.4197115384615384, 'g-mean': np.float64(0.7118270355896783), 'roc-auc': 0.8091632692681032, 'avg-roc-auc': 0.8091632692681032, 'pr-auc': 0.76916088460186, 'brier-score': 0.17675435457355332, 'log-loss': 0.5235689343387016}
2026-03-28 11:49:05 | INFO     | pepbenchmark | [RUN_MULTI] running seed=46, fold=4
2026-03-28 11:49:05 | INFO     | pepbenchmark | [RUN] model=facebook/esm2_t30_150M_UR50D | seed=46, fold=4, split=hybrid_split
2026-03-28 11:49:05 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====4=== successfully

Some weights of EsmForSequenceClassification were not initialized from the model checkpoint at facebook/esm2_t30_150M_UR50D and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

dict_keys(['fasta', 'label'])
dict_keys(['fasta', 'label'])
2026-03-28 11:49:07 | INFO     | pepbenchmark | [TRAIN] model=facebook/esm2_t30_150M_UR50D, split=hybrid_split, fold=4, seed=46

2026-03-28 11:51:34 | INFO     | pepbenchmark | [TRAIN DONE] facebook/esm2_t30_150M_UR50D in 146.81s
2026-03-28 11:51:40 | INFO     | pepbenchmark | [SAVE MODEL] saved to ./results/ace_inhibitory/facebook_esm2_t30_150M_UR50D/hybrid_split/fold_4_seed_46/model

2026-03-28 11:51:43 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.7539766702014846, 'balanced-accuracy': 0.7502319401909566, 'precision': 0.7204362801377727, 'recall': 0.85724043715847, 'specificity': np.float64(0.6432234432234433), 'f1': 0.7829070492825951, 'micro-f1': 0.7539766702014846, 'macro-f1': 0.7495285654243318, 'weighted-f1': 0.7506966353790748, 'mcc': 0.5141274067968588, 'kappa': 0.5039340441066432, 'g-mean': np.float64(0.7425612066755445), 'roc-auc': 0.8428378770591884, 'avg-roc-auc': 0.8428378770591884, 'pr-auc': 0.8527111668141385, 'brier-score': 0.16749971273745667, 'log-loss': 0.5081836429694423}

2026-03-28 11:51:43 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.6883852691218131, 'balanced-accuracy': 0.6915287244401168, 'precision': 0.6333333333333333, 'recall': 0.7215189873417721, 'specificity': np.float64(0.6615384615384615), 'f1': 0.6745562130177515, 'micro-f1': 0.6883852691218131, 'macro-f1': 0.6878215847697453, 'weighted-f1': 0.6892120061715123, 'mcc': 0.3810223550624114, 'kappa': 0.3780632347759233, 'g-mean': np.float64(0.6908781085378698), 'roc-auc': 0.7576760791950664, 'avg-roc-auc': 0.7576760791950664, 'pr-auc': 0.7528413070821934, 'brier-score': 0.2047825035529527, 'log-loss': 0.5955825910243268}

2026-03-28 11:51:44 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.7098591549295775, 'balanced-accuracy': 0.7214340860837676, 'precision': 0.6323529411764706, 'recall': 0.821656050955414, 'specificity': np.float64(0.6212121212121212), 'f1': 0.7146814404432132, 'micro-f1': 0.7098591549295775, 'macro-f1': 0.7097762503075665, 'weighted-f1': 0.7092097353904918, 'mcc': 0.44489070652850937, 'kappa': 0.4295542832181469, 'g-mean': np.float64(0.7144387295778327), 'roc-auc': 0.7938300199446695, 'avg-roc-auc': 0.7938300199446695, 'pr-auc': 0.7455415574020091, 'brier-score': 0.19213686365867522, 'log-loss': 0.5676155619630879}
2026-03-28 11:51:44 | INFO     | pepbenchmark | [RUN_MULTI DONE] total runs: 5
   random_seed  fold_seed                    model_name    split_type  \
0           42          0  facebook/esm2_t30_150M_UR50D  hybrid_split
1           43          1  facebook/esm2_t30_150M_UR50D  hybrid_split
2           44          2  facebook/esm2_t30_150M_UR50D  hybrid_split
3           45          3  facebook/esm2_t30_150M_UR50D  hybrid_split
4           46          4  facebook/esm2_t30_150M_UR50D  hybrid_split

   train_samples  valid_samples  test_samples  training_time  train_accuracy  \
0           2829            353           355     152.996068        0.818664
1           2829            353           355     149.977878        0.835631
2           2829            353           355     153.481135        0.869212
3           2829            353           355     150.603342        0.813715
4           2829            353           355     146.808589        0.753977

   train_balanced-accuracy  ...  test_macro-f1  test_weighted-f1  test_mcc  \
0                 0.817636  ...       0.734451          0.735932  0.472705
1                 0.837646  ...       0.698129          0.702074  0.409822
2                 0.869793  ...       0.700731          0.705884  0.410030
3                 0.812988  ...       0.709521          0.713699  0.420693
4                 0.750232  ...       0.709776          0.709210  0.444891

   test_kappa  test_g-mean  test_roc-auc  test_avg-roc-auc  test_pr-auc  \
0    0.470267     0.737276      0.799031          0.799031     0.756864
1    0.401912     0.687837      0.800632          0.800632     0.778245
2    0.405012     0.691408      0.794840          0.794840     0.773072
3    0.419712     0.711827      0.809163          0.809163     0.769161
4    0.429554     0.714439      0.793830          0.793830     0.745542

   test_brier-score  test_log-loss
0          0.186454       0.555592
1          0.186776       0.548624
2          0.184072       0.544972
3          0.176754       0.523569
4          0.192137       0.567616

[5 rows x 59 columns]
{'mean': 0.7994992138220309, 'std': 0.005454303160524348, 'min': 0.7938300199446695, 'max': 0.8091632692681032}

# 2. canonical peptide regression

In [ ]:
from pepbenchmark.model.plm_model import build_plm_model
from pepbenchmark.dataset_manager.single_dataset import SinglePeptideDatasetManager


dataset = SinglePeptideDatasetManager(
    "antimicrobial_P_aeruginosa_mic",
    official_feature_names=["graph", "label"],
    dataset_dir="../../PepBenchData/PepBenchData-50",
)
runner = build_plm_model(
    model_type="plm",      
    dataset=dataset,
    task_type="regression",
    model_name="facebook/esm2_t30_150M_UR50D",    
    epochs=50,
    batch_size=64,
    learning_rate=5e-5,
    weight_decay=0,
    early_stopping_patience=5,
)


multi_results = runner.run_multi(
    run_seeds=[42, 43, 44, 45, 46],
    fold_seeds=[0, 1, 2, 3, 4],
    split_type="hybrid_split",   
    base_dir="./results",
)
print(multi_results.to_dataframe())
summary = multi_results.get_summary_stats()
print(summary["test_mae"])

2026-03-28 11:34:51 | INFO     | pepbenchmark | Loaded official feature: graph
2026-03-28 11:34:51 | INFO     | pepbenchmark | Loaded official feature: label
2026-03-28 11:34:51 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:34:51 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:34:51 | INFO     | pepbenchmark | [RUN] gin_default | seed=42, fold=0, split=hybrid_split
2026-03-28 11:34:51 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====0=== successfully
2026-03-28 11:34:52 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:34:52 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:34:52 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:34:52 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:34:52 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 4.2582, Val Loss: 0.7727
2026-03-28 11:34:54 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.5585, Val Loss: 0.6054
2026-03-28 11:34:56 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.5255, Val Loss: 0.5354
2026-03-28 11:34:57 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 12
2026-03-28 11:34:57 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.39854629251678453, 'rmse': np.float64(0.6313052292804049), 'mae': 0.5156396768191023, 'r2': 0.13051655605747703, 'pcc': np.float64(0.3842005762861521), 'spearman': np.float64(0.3752485475516124)}
2026-03-28 11:34:57 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.5122102631861959, 'rmse': np.float64(0.7156886635864759), 'mae': 0.5718108721127446, 'r2': 0.14537979424280334, 'pcc': np.float64(0.3937952535641145), 'spearman': np.float64(0.3669404913476561)}
2026-03-28 11:34:57 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.32574271722856707, 'rmse': np.float64(0.5707387469136532), 'mae': 0.46272138622433145, 'r2': 0.2307297133390842, 'pcc': np.float64(0.49784401257906624), 'spearman': np.float64(0.45304027956296916)}
2026-03-28 11:34:57 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:34:57 | INFO     | pepbenchmark | [RUN] gin_default | seed=43, fold=1, split=hybrid_split
2026-03-28 11:34:57 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====1=== successfully
2026-03-28 11:34:58 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:34:58 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:34:58 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:34:58 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:34:58 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 2.2663, Val Loss: 0.9592
2026-03-28 11:35:00 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.6674, Val Loss: 0.5356
2026-03-28 11:35:02 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.5234, Val Loss: 0.5422
2026-03-28 11:35:03 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 13
2026-03-28 11:35:03 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.3869416609316625, 'rmse': np.float64(0.6220463495043296), 'mae': 0.5029656774565209, 'r2': 0.15234662120460019, 'pcc': np.float64(0.3950009935014519), 'spearman': np.float64(0.3983833559503712)}
2026-03-28 11:35:03 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.4521968367546987, 'rmse': np.float64(0.67245582513255), 'mae': 0.5493474196667639, 'r2': 0.23815022745676562, 'pcc': np.float64(0.48858869681121087), 'spearman': np.float64(0.4283200532073302)}
2026-03-28 11:35:04 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.397781641441331, 'rmse': np.float64(0.6306993272878377), 'mae': 0.5026646862994104, 'r2': 0.18679219892189802, 'pcc': np.float64(0.4551695865476941), 'spearman': np.float64(0.40603518326219057)}
2026-03-28 11:35:04 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:35:04 | INFO     | pepbenchmark | [RUN] gin_default | seed=44, fold=2, split=hybrid_split
2026-03-28 11:35:04 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====2=== successfully
2026-03-28 11:35:04 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:35:04 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:35:04 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:35:04 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:35:05 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 2.6923, Val Loss: 1.5225
2026-03-28 11:35:06 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.5151, Val Loss: 0.6710
2026-03-28 11:35:08 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.5419, Val Loss: 0.5435
2026-03-28 11:35:10 | INFO     | pepbenchmark | [EPOCH 15/50] Train Loss: 0.4259, Val Loss: 0.5203
2026-03-28 11:35:12 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 18
2026-03-28 11:35:12 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.35439868938110947, 'rmse': np.float64(0.5953139418669022), 'mae': 0.48145906601746524, 'r2': 0.2126076174309378, 'pcc': np.float64(0.4762140724126952), 'spearman': np.float64(0.44638195877350156)}
2026-03-28 11:35:12 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.47485387832197856, 'rmse': np.float64(0.6890964216435742), 'mae': 0.5485526030170638, 'r2': 0.17806983457326275, 'pcc': np.float64(0.42900308096507783), 'spearman': np.float64(0.4348984768273586)}
2026-03-28 11:35:12 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.4527229137109262, 'rmse': np.float64(0.6728468724092623), 'mae': 0.542290285642215, 'r2': 0.16452868500774398, 'pcc': np.float64(0.4166158227008255), 'spearman': np.float64(0.3842445672769682)}
2026-03-28 11:35:12 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:35:12 | INFO     | pepbenchmark | [RUN] gin_default | seed=45, fold=3, split=hybrid_split
2026-03-28 11:35:12 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====3=== successfully
2026-03-28 11:35:12 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:35:12 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:35:12 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:35:12 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:35:13 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 2.5434, Val Loss: 0.6896
2026-03-28 11:35:15 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.6145, Val Loss: 0.4135
2026-03-28 11:35:17 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.4866, Val Loss: 0.3440
2026-03-28 11:35:18 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 13
2026-03-28 11:35:18 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.3881525701833545, 'rmse': np.float64(0.6230189163928769), 'mae': 0.5054056139169855, 'r2': 0.18684847867779109, 'pcc': np.float64(0.4491138793402598), 'spearman': np.float64(0.4261726640577023)}
2026-03-28 11:35:18 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.3391632324452506, 'rmse': np.float64(0.5823772252116755), 'mae': 0.4615006748486885, 'r2': 0.18761050290074444, 'pcc': np.float64(0.43468284920083533), 'spearman': np.float64(0.37233053629200336)}
2026-03-28 11:35:18 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.43309850290652174, 'rmse': np.float64(0.6581021979195342), 'mae': 0.5318908711282799, 'r2': 0.18745399664743922, 'pcc': np.float64(0.43488545049237215), 'spearman': np.float64(0.4360448894927176)}
2026-03-28 11:35:18 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:35:18 | INFO     | pepbenchmark | [RUN] gin_default | seed=46, fold=4, split=hybrid_split
2026-03-28 11:35:18 | INFO     | pepbenchmark | Set official split ===hybrid_split=== with seed ====4=== successfully
2026-03-28 11:35:18 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:35:18 | INFO     | pepbenchmark | [DATA LOADERS] Train=1192, Valid=149, Test=149
2026-03-28 11:35:18 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:35:18 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:35:19 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 2.4315, Val Loss: 1.3402
2026-03-28 11:35:21 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.5878, Val Loss: 0.4928
2026-03-28 11:35:23 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.4958, Val Loss: 0.4924
2026-03-28 11:35:23 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 11
2026-03-28 11:35:23 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.4090048216394807, 'rmse': np.float64(0.6395348478695126), 'mae': 0.5197814542557201, 'r2': 0.13447224437790495, 'pcc': np.float64(0.387166907241916), 'spearman': np.float64(0.34557777170592374)}
2026-03-28 11:35:23 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.39159518916227215, 'rmse': np.float64(0.6257756699986603), 'mae': 0.4970911843639692, 'r2': 0.07289706112713246, 'pcc': np.float64(0.2988084447249878), 'spearman': np.float64(0.30026779743424614)}
2026-03-28 11:35:23 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.4616065827535776, 'rmse': np.float64(0.6794163544937505), 'mae': 0.5335582371351103, 'r2': 0.14221899940304294, 'pcc': np.float64(0.3846019968418141), 'spearman': np.float64(0.42138353389149513)}
   random_seed  fold_seed   model_name  training_time  epochs_trained  \
0           42          0  gin_default       5.082075              12
1           43          1  gin_default       5.401377              13
2           44          2  gin_default       7.485836              18
3           45          3  gin_default       5.376601              13
4           46          4  gin_default       4.550243              11

   best_val_loss  train_samples  valid_samples  test_samples  train_mse  ...  \
0       0.517028           1192            149           149   0.398546  ...
1       0.510177           1192            149           149   0.386942  ...
2       0.509165           1192            149           149   0.354399  ...
3       0.325823           1192            149           149   0.388153  ...
4       0.415680           1192            149           149   0.409005  ...

   valid_mae  valid_r2  valid_pcc  valid_spearman  test_mse  test_rmse  \
0   0.571811  0.145380   0.393795        0.366940  0.325743   0.570739
1   0.549347  0.238150   0.488589        0.428320  0.397782   0.630699
2   0.548553  0.178070   0.429003        0.434898  0.452723   0.672847
3   0.461501  0.187611   0.434683        0.372331  0.433099   0.658102
4   0.497091  0.072897   0.298808        0.300268  0.461607   0.679416

   test_mae   test_r2  test_pcc  test_spearman
0  0.462721  0.230730  0.497844       0.453040
1  0.502665  0.186792  0.455170       0.406035
2  0.542290  0.164529  0.416616       0.384245
3  0.531891  0.187454  0.434885       0.436045
4  0.533558  0.142219  0.384602       0.421384

[5 rows x 27 columns]
{'mean': 0.5146250932858695, 'std': 0.032630430699903464, 'min': 0.46272138622433145, 'max': 0.542290285642215}

# 3. non-canonical peptide classification

In [ ]:
from pepbenchmark.model.plm_model import build_plm_model
from pepbenchmark.dataset_manager.single_dataset import SinglePeptideDatasetManager

dataset = SinglePeptideDatasetManager(
    "nc-antifungal",
    official_feature_names=["graph", "label"],
    dataset_dir="../../PepBenchData/PepBenchData-50",
)
runner = build_plm_model(
    model_type="plm",      
    dataset=dataset,
    task_type="binary_classification",
    model_name="facebook/esm2_t30_150M_UR50D",    
    epochs=50,
    batch_size=64,
    learning_rate=5e-5,
    weight_decay=0,
    early_stopping_patience=5,
)


multi_results = runner.run_multi(
    run_seeds=[42, 43, 44, 45, 46],
    fold_seeds=[0, 1, 2, 3, 4],
    split_type="ecfp_split",   
    base_dir="./results",
)
print(multi_results.to_dataframe())
summary = multi_results.get_summary_stats()
print(summary["test_roc-auc"])

2026-03-28 11:35:47 | INFO     | pepbenchmark | Loaded official feature: graph
2026-03-28 11:35:47 | INFO     | pepbenchmark | Loaded official feature: label
2026-03-28 11:35:47 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:35:47 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:35:47 | INFO     | pepbenchmark | [RUN] gin_default | seed=42, fold=0, split=ecfp_split
2026-03-28 11:35:47 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====0=== successfully
2026-03-28 11:35:47 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:47 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:47 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:35:47 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:35:47 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 0.8674, Val Loss: 6.5078
2026-03-28 11:35:48 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.4823, Val Loss: 0.8513
2026-03-28 11:35:48 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.8653, Val Loss: 0.5399
2026-03-28 11:35:49 | INFO     | pepbenchmark | [EPOCH 15/50] Train Loss: 0.5495, Val Loss: 1.1026
2026-03-28 11:35:49 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 15
2026-03-28 11:35:49 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.6801242236024845, 'balanced-accuracy': 0.712525061917679, 'precision': 0.925531914893617, 'recall': 0.47540983606557374, 'specificity': np.float64(0.9496402877697842), 'f1': 0.628158844765343, 'micro-f1': 0.6801242236024845, 'macro-f1': 0.6737524469058322, 'weighted-f1': 0.6675222652468834, 'mcc': 0.46306477068038004, 'kappa': 0.3946705603212265, 'g-mean': np.float64(0.6719139331267788), 'roc-auc': 0.9069072610763848, 'avg-roc-auc': 0.9069072610763848, 'pr-auc': 0.9270966036549121, 'brier-score': 0.20732093280851283, 'log-loss': 0.6182719431878566}
2026-03-28 11:35:49 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.75, 'balanced-accuracy': 0.5666666666666667, 'precision': 0.5, 'recall': 0.2, 'specificity': np.float64(0.9333333333333333), 'f1': 0.2857142857142857, 'micro-f1': 0.75, 'macro-f1': 0.5670995670995671, 'weighted-f1': 0.7077922077922079, 'mcc': 0.19245008972987526, 'kappa': 0.16666666666666663, 'g-mean': np.float64(0.43204937989385733), 'roc-auc': 0.72, 'avg-roc-auc': 0.72, 'pr-auc': 0.5071017952635599, 'brier-score': 0.17007089545652398, 'log-loss': 0.5398999072652766}
2026-03-28 11:35:49 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.7560975609756098, 'balanced-accuracy': 0.5338709677419355, 'precision': 0.5, 'recall': 0.1, 'specificity': np.float64(0.967741935483871), 'f1': 0.16666666666666666, 'micro-f1': 0.7560975609756098, 'macro-f1': 0.5119047619047619, 'weighted-f1': 0.6887340301974448, 'mcc': 0.13504892964960413, 'kappa': 0.09292035398230081, 'g-mean': np.float64(0.3110855084191276), 'roc-auc': 0.8129032258064516, 'avg-roc-auc': 0.8129032258064516, 'pr-auc': 0.4977225114067219, 'brier-score': 0.17439549069231983, 'log-loss': 0.510049807801934}
2026-03-28 11:35:49 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:35:49 | INFO     | pepbenchmark | [RUN] gin_default | seed=43, fold=1, split=ecfp_split
2026-03-28 11:35:49 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====1=== successfully
2026-03-28 11:35:49 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:49 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:49 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:35:49 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:35:49 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 0.8245, Val Loss: 1.0315
2026-03-28 11:35:50 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.4852, Val Loss: 0.6696
2026-03-28 11:35:50 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 8
2026-03-28 11:35:50 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.5683229813664596, 'balanced-accuracy': 0.6132246376811594, 'precision': 0.8461538461538461, 'recall': 0.29891304347826086, 'specificity': np.float64(0.927536231884058), 'f1': 0.44176706827309237, 'micro-f1': 0.5683229813664596, 'macro-f1': 0.5449341670479386, 'weighted-f1': 0.5301960100801034, 'mcc': 0.27918761583008006, 'kappa': 0.20441537203597715, 'g-mean': np.float64(0.526547887669129), 'roc-auc': 0.8243935097668558, 'avg-roc-auc': 0.8243935097668558, 'pr-auc': 0.8081058854381091, 'brier-score': 0.27007526165850926, 'log-loss': 0.7431904665994225}
2026-03-28 11:35:50 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.675, 'balanced-accuracy': 0.5219435736677116, 'precision': 0.3333333333333333, 'recall': 0.18181818181818182, 'specificity': np.float64(0.8620689655172413), 'f1': 0.23529411764705882, 'micro-f1': 0.675, 'macro-f1': 0.5144724556489262, 'weighted-f1': 0.6401027077497666, 'mcc': 0.05488044326015419, 'kappa': 0.05109489051094884, 'g-mean': np.float64(0.3959037912324479), 'roc-auc': 0.6645768025078369, 'avg-roc-auc': 0.6645768025078369, 'pr-auc': 0.3881876133020298, 'brier-score': 0.22026005608913252, 'log-loss': 0.6505350712848548}
2026-03-28 11:35:50 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.8536585365853658, 'balanced-accuracy': 0.6723484848484849, 'precision': 0.75, 'recall': 0.375, 'specificity': np.float64(0.9696969696969697), 'f1': 0.5, 'micro-f1': 0.8536585365853658, 'macro-f1': 0.7071428571428571, 'weighted-f1': 0.8334494773519163, 'mcc': 0.46037164953117576, 'kappa': 0.4252336448598131, 'g-mean': np.float64(0.6030226891555273), 'roc-auc': 0.8181818181818181, 'avg-roc-auc': 0.8181818181818181, 'pr-auc': 0.6576923076923077, 'brier-score': 0.11757836223497678, 'log-loss': 0.3833437505027132}
2026-03-28 11:35:50 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:35:50 | INFO     | pepbenchmark | [RUN] gin_default | seed=44, fold=2, split=ecfp_split
2026-03-28 11:35:50 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====2=== successfully
2026-03-28 11:35:50 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:50 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:50 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:35:50 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:35:50 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 0.7058, Val Loss: 0.4786
2026-03-28 11:35:51 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.5375, Val Loss: 1.2501
2026-03-28 11:35:51 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.4925, Val Loss: 0.9469
2026-03-28 11:35:52 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 12
2026-03-28 11:35:52 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.7732919254658385, 'balanced-accuracy': 0.7865875161631597, 'precision': 0.8913043478260869, 'recall': 0.6795580110497238, 'specificity': np.float64(0.8936170212765957), 'f1': 0.7711598746081505, 'micro-f1': 0.7732919254658385, 'macro-f1': 0.7732722449963829, 'weighted-f1': 0.773009838736975, 'mcc': 0.5746291499107219, 'kappa': 0.5544899738448126, 'g-mean': np.float64(0.7792718432093527), 'roc-auc': 0.8958504760785236, 'avg-roc-auc': 0.8958504760785236, 'pr-auc': 0.9226367179698618, 'brier-score': 0.1481563742175778, 'log-loss': 0.4588483255307491}
2026-03-28 11:35:52 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.825, 'balanced-accuracy': 0.7688172043010753, 'precision': 0.6, 'recall': 0.6666666666666666, 'specificity': np.float64(0.8709677419354839), 'f1': 0.631578947368421, 'micro-f1': 0.825, 'macro-f1': 0.7584124245038826, 'weighted-f1': 0.8281708369283866, 'mcc': 0.5184758473652127, 'kappa': 0.5172413793103448, 'g-mean': np.float64(0.762000762001143), 'roc-auc': 0.9032258064516129, 'avg-roc-auc': 0.9032258064516129, 'pr-auc': 0.7021723646723647, 'brier-score': 0.1242605689777502, 'log-loss': 0.3960204027993993}
2026-03-28 11:35:52 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.6097560975609756, 'balanced-accuracy': 0.5288461538461539, 'precision': 0.36363636363636365, 'recall': 0.3076923076923077, 'specificity': np.float64(0.75), 'f1': 0.3333333333333333, 'micro-f1': 0.6097560975609756, 'macro-f1': 0.5287356321839081, 'weighted-f1': 0.6002242781048499, 'mcc': 0.06059149009001736, 'kappa': 0.06017191977077363, 'g-mean': np.float64(0.4803844614152614), 'roc-auc': 0.6510989010989011, 'avg-roc-auc': 0.6510989010989011, 'pr-auc': 0.4116537886629368, 'brier-score': 0.25519973879761665, 'log-loss': 0.7639076559533067}
2026-03-28 11:35:52 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:35:52 | INFO     | pepbenchmark | [RUN] gin_default | seed=45, fold=3, split=ecfp_split
2026-03-28 11:35:52 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====3=== successfully
2026-03-28 11:35:52 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:52 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:52 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:35:52 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:35:52 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 0.6500, Val Loss: 1.3579
2026-03-28 11:35:52 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.5572, Val Loss: 0.8671
2026-03-28 11:35:53 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.5031, Val Loss: 0.6140
2026-03-28 11:35:54 | INFO     | pepbenchmark | [EPOCH 15/50] Train Loss: 0.6340, Val Loss: 0.7138
2026-03-28 11:35:54 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 15
2026-03-28 11:35:54 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.7888198757763976, 'balanced-accuracy': 0.7975274725274726, 'precision': 0.875, 'recall': 0.7307692307692307, 'specificity': np.float64(0.8642857142857143), 'f1': 0.7964071856287425, 'micro-f1': 0.7888198757763976, 'macro-f1': 0.7885261734595326, 'weighted-f1': 0.7895541315685598, 'mcc': 0.5908952866786167, 'kappa': 0.5806970509383378, 'g-mean': np.float64(0.7947285112498522), 'roc-auc': 0.9124803767660911, 'avg-roc-auc': 0.9124803767660911, 'pr-auc': 0.9321748120846832, 'brier-score': 0.12830011866676286, 'log-loss': 0.3886633530008091}
2026-03-28 11:35:54 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.7, 'balanced-accuracy': 0.6666666666666667, 'precision': 0.6153846153846154, 'recall': 0.5333333333333333, 'specificity': np.float64(0.8), 'f1': 0.5714285714285714, 'micro-f1': 0.7, 'macro-f1': 0.6703296703296704, 'weighted-f1': 0.695054945054945, 'mcc': 0.34454092941446796, 'kappa': 0.34246575342465757, 'g-mean': np.float64(0.6531972647421809), 'roc-auc': 0.7226666666666667, 'avg-roc-auc': 0.7226666666666667, 'pr-auc': 0.6843266411008346, 'brier-score': 0.20635365655299406, 'log-loss': 0.6140211057749104}
2026-03-28 11:35:54 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.7317073170731707, 'balanced-accuracy': 0.6357142857142857, 'precision': 0.2727272727272727, 'recall': 0.5, 'specificity': np.float64(0.7714285714285715), 'f1': 0.35294117647058826, 'micro-f1': 0.7317073170731707, 'macro-f1': 0.5918552036199095, 'weighted-f1': 0.7608431740426003, 'mcc': 0.21652509527331207, 'kappa': 0.2017699115044248, 'g-mean': np.float64(0.6210590034081188), 'roc-auc': 0.8, 'avg-roc-auc': 0.8, 'pr-auc': 0.638888888888889, 'brier-score': 0.16291427885916385, 'log-loss': 0.48214187268194536}
2026-03-28 11:35:54 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:35:54 | INFO     | pepbenchmark | [RUN] gin_default | seed=46, fold=4, split=ecfp_split
2026-03-28 11:35:54 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====4=== successfully
2026-03-28 11:35:54 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:54 | INFO     | pepbenchmark | [DATA LOADERS] Train=322, Valid=40, Test=41
2026-03-28 11:35:54 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:35:54 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:35:54 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 0.8899, Val Loss: 0.9364
2026-03-28 11:35:55 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.4697, Val Loss: 0.8343
2026-03-28 11:35:55 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.5184, Val Loss: 0.6690
2026-03-28 11:35:55 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 11
2026-03-28 11:35:55 | INFO     | pepbenchmark | [METRICS] train: {'accuracy': 0.7080745341614907, 'balanced-accuracy': 0.7324948081971709, 'precision': 0.9065420560747663, 'recall': 0.5359116022099447, 'specificity': np.float64(0.9290780141843972), 'f1': 0.6736111111111112, 'micro-f1': 0.7080745341614907, 'macro-f1': 0.7047830836454432, 'weighted-f1': 0.7009107889206815, 'mcc': 0.4897573696693855, 'kappa': 0.43950224065775334, 'g-mean': np.float64(0.7056229071959003), 'roc-auc': 0.8303358018886406, 'avg-roc-auc': 0.8303358018886406, 'pr-auc': 0.8753441933633345, 'brier-score': 0.20679812217175303, 'log-loss': 0.6171283365512976}
2026-03-28 11:35:55 | INFO     | pepbenchmark | [METRICS] valid: {'accuracy': 0.7, 'balanced-accuracy': 0.5956112852664577, 'precision': 0.4444444444444444, 'recall': 0.36363636363636365, 'specificity': np.float64(0.8275862068965517), 'f1': 0.4, 'micro-f1': 0.7, 'macro-f1': 0.6000000000000001, 'weighted-f1': 0.6900000000000001, 'mcc': 0.20447131584993633, 'kappa': 0.2026578073089701, 'g-mean': np.float64(0.5485803850589933), 'roc-auc': 0.6645768025078369, 'avg-roc-auc': 0.6645768025078369, 'pr-auc': 0.4473911025294425, 'brier-score': 0.20134703338602716, 'log-loss': 0.5891178082553811}
2026-03-28 11:35:55 | INFO     | pepbenchmark | [METRICS] test: {'accuracy': 0.7317073170731707, 'balanced-accuracy': 0.5863636363636364, 'precision': 0.5, 'recall': 0.2727272727272727, 'specificity': np.float64(0.9), 'f1': 0.35294117647058826, 'micro-f1': 0.7317073170731707, 'macro-f1': 0.5918552036199095, 'weighted-f1': 0.7025714601037413, 'mcc': 0.21652509527331207, 'kappa': 0.2017699115044248, 'g-mean': np.float64(0.4954336943068623), 'roc-auc': 0.7090909090909091, 'avg-roc-auc': 0.7090909090909091, 'pr-auc': 0.5446440596440596, 'brier-score': 0.18033052628114676, 'log-loss': 0.545744773119874}
   random_seed  fold_seed   model_name  training_time  epochs_trained  \
0           42          0  gin_default       1.739374              15
1           43          1  gin_default       0.816785               8
2           44          2  gin_default       1.266985              12
3           45          3  gin_default       1.606801              15
4           46          4  gin_default       1.280089              11

   best_val_loss  train_samples  valid_samples  test_samples  train_accuracy  \
0       0.539900            322             40            41        0.680124
1       0.650535            322             40            41        0.568323
2       0.396020            322             40            41        0.773292
3       0.614021            322             40            41        0.788820
4       0.589118            322             40            41        0.708075

   ...  test_macro-f1  test_weighted-f1  test_mcc  test_kappa  test_g-mean  \
0  ...       0.511905          0.688734  0.135049    0.092920     0.311086
1  ...       0.707143          0.833449  0.460372    0.425234     0.603023
2  ...       0.528736          0.600224  0.060591    0.060172     0.480384
3  ...       0.591855          0.760843  0.216525    0.201770     0.621059
4  ...       0.591855          0.702571  0.216525    0.201770     0.495434

   test_roc-auc  test_avg-roc-auc  test_pr-auc  test_brier-score  \
0      0.812903          0.812903     0.497723          0.174395
1      0.818182          0.818182     0.657692          0.117578
2      0.651099          0.651099     0.411654          0.255200
3      0.800000          0.800000     0.638889          0.162914
4      0.709091          0.709091     0.544644          0.180331

   test_log-loss
0       0.510050
1       0.383344
2       0.763908
3       0.482142
4       0.545745

[5 rows x 60 columns]
{'mean': 0.758254970835616, 'std': 0.0745315948319986, 'min': 0.6510989010989011, 'max': 0.8181818181818181}

# 4. non-canonical peptide regression

In [ ]:
from pepbenchmark.model.plm_model import build_plm_model
from pepbenchmark.dataset_manager.single_dataset import SinglePeptideDatasetManager


dataset = SinglePeptideDatasetManager(
    "nc-cpp_pampa",
    official_feature_names=["graph", "label"],
    dataset_dir="../../PepBenchData/PepBenchData-50",
)
runner = build_plm_model(
    model_type="plm",      
    dataset=dataset,
    task_type="regression",
    model_name="facebook/esm2_t30_150M_UR50D",    
    epochs=50,
    batch_size=64,
    learning_rate=5e-5,
    weight_decay=0,
    early_stopping_patience=5,
)


multi_results = runner.run_multi(
    run_seeds=[42, 43, 44, 45, 46],
    fold_seeds=[0, 1, 2, 3, 4],
    split_type="ecfp_split",   
    base_dir="./results",
)
print(multi_results.to_dataframe())
summary = multi_results.get_summary_stats()
print(summary["test_mae"])

2026-03-28 11:24:03 | INFO     | pepbenchmark | Loaded official feature: graph
2026-03-28 11:24:03 | INFO     | pepbenchmark | Loaded official feature: label
2026-03-28 11:24:03 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:24:03 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:24:03 | INFO     | pepbenchmark | [RUN] gin_default | seed=42, fold=0, split=ecfp_split
2026-03-28 11:24:03 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====0=== successfully
2026-03-28 11:24:04 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:24:05 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:24:05 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:24:05 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:24:06 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 26.9353, Val Loss: 10.2429
2026-03-28 11:24:11 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.4562, Val Loss: 8.6932
2026-03-28 11:24:17 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 9
2026-03-28 11:24:17 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.36993937311825653, 'rmse': np.float64(0.6082264159983982), 'mae': 0.46040769064614556, 'r2': 0.29196309700670586, 'pcc': np.float64(0.5835697953455332), 'spearman': np.float64(0.5743140506590387)}
2026-03-28 11:24:17 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.7855669123144776, 'rmse': np.float64(0.886322126720572), 'mae': 0.733341964792829, 'r2': 0.2127921401003141, 'pcc': np.float64(0.5200237300807151), 'spearman': np.float64(0.5806414752790369)}
2026-03-28 11:24:18 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.8621242141336843, 'rmse': np.float64(0.9285064426990716), 'mae': 0.8066835081902262, 'r2': -0.005010441964557355, 'pcc': np.float64(0.39541872795306166), 'spearman': np.float64(0.4127885338599853)}
2026-03-28 11:24:18 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:24:18 | INFO     | pepbenchmark | [RUN] gin_default | seed=43, fold=1, split=ecfp_split
2026-03-28 11:24:18 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====1=== successfully
2026-03-28 11:24:18 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:24:19 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:24:19 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:24:19 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:24:21 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 26.7286, Val Loss: 24.2724
2026-03-28 11:24:26 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.4443, Val Loss: 1.4403
2026-03-28 11:24:30 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 8
2026-03-28 11:24:30 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.45431590870173255, 'rmse': np.float64(0.6740296052116201), 'mae': 0.5409387214967134, 'r2': 0.13046622606413005, 'pcc': np.float64(0.525207167747097), 'spearman': np.float64(0.5274261560222857)}
2026-03-28 11:24:30 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.813550254736426, 'rmse': np.float64(0.9019702072332688), 'mae': 0.746939373153183, 'r2': 0.18981831512402303, 'pcc': np.float64(0.4883247521245241), 'spearman': np.float64(0.48659362203075845)}
2026-03-28 11:24:30 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.9009200250588282, 'rmse': np.float64(0.9491680699743477), 'mae': 0.8076126462588864, 'r2': -0.07784202897484938, 'pcc': np.float64(0.2998565554787629), 'spearman': np.float64(0.26612224202178886)}
2026-03-28 11:24:31 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:24:31 | INFO     | pepbenchmark | [RUN] gin_default | seed=44, fold=2, split=ecfp_split
2026-03-28 11:24:31 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====2=== successfully
2026-03-28 11:24:32 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:24:32 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:24:32 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:24:32 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:24:34 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 26.7683, Val Loss: 32.2506
2026-03-28 11:24:39 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.4560, Val Loss: 1.5447
2026-03-28 11:24:45 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.3889, Val Loss: 0.8243
2026-03-28 11:24:48 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 13
2026-03-28 11:24:49 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.31845022543664486, 'rmse': np.float64(0.5643139422667536), 'mae': 0.41190874337123834, 'r2': 0.38999690296543765, 'pcc': np.float64(0.6704822561851695), 'spearman': np.float64(0.6265026691521315)}
2026-03-28 11:24:49 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.6444639801246768, 'rmse': np.float64(0.8027851394518192), 'mae': 0.6426610440400615, 'r2': 0.36416313979155834, 'pcc': np.float64(0.6040555563639254), 'spearman': np.float64(0.6083052971516798)}
2026-03-28 11:24:49 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.6690123800193821, 'rmse': np.float64(0.817931769782408), 'mae': 0.666986948448411, 'r2': 0.1975208994222334, 'pcc': np.float64(0.4929302023112433), 'spearman': np.float64(0.49618083499603677)}
2026-03-28 11:24:49 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:24:49 | INFO     | pepbenchmark | [RUN] gin_default | seed=45, fold=3, split=ecfp_split
2026-03-28 11:24:49 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====3=== successfully
2026-03-28 11:24:50 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:24:51 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:24:51 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:24:51 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:24:52 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 27.0491, Val Loss: 13.3943
2026-03-28 11:24:57 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.4319, Val Loss: 1.0368
2026-03-28 11:25:02 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.3698, Val Loss: 1.1952
2026-03-28 11:25:03 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 11
2026-03-28 11:25:04 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.4067275392110403, 'rmse': np.float64(0.6377519417540336), 'mae': 0.4604771385233919, 'r2': 0.21805978647846203, 'pcc': np.float64(0.5565589746195662), 'spearman': np.float64(0.5319428446920468)}
2026-03-28 11:25:04 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.915183840425887, 'rmse': np.float64(0.9566524135891191), 'mae': 0.7511061479576691, 'r2': 0.10059625186657484, 'pcc': np.float64(0.3478828517146411), 'spearman': np.float64(0.32727918144308904)}
2026-03-28 11:25:04 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.8879453737846472, 'rmse': np.float64(0.9423085342840991), 'mae': 0.7854568927496715, 'r2': -0.03352842717321103, 'pcc': np.float64(0.2068822028770223), 'spearman': np.float64(0.21714539250681733)}
2026-03-28 11:25:04 | INFO     | pepbenchmark | [GNN] Using device: cuda
2026-03-28 11:25:04 | INFO     | pepbenchmark | [RUN] gin_default | seed=46, fold=4, split=ecfp_split
2026-03-28 11:25:04 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====4=== successfully
2026-03-28 11:25:05 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:25:06 | INFO     | pepbenchmark | [DATA LOADERS] Train=5576, Valid=697, Test=697
2026-03-28 11:25:06 | INFO     | pepbenchmark | [BUILD MODEL DONE] gin_default | num_tasks=1
2026-03-28 11:25:06 | INFO     | pepbenchmark | [GNN TRAINING] Starting for 50 epochs with patience=5
2026-03-28 11:25:07 | INFO     | pepbenchmark | [EPOCH 1/50] Train Loss: 26.3446, Val Loss: 13.5021
2026-03-28 11:25:12 | INFO     | pepbenchmark | [EPOCH 5/50] Train Loss: 0.4590, Val Loss: 0.8942
2026-03-28 11:25:17 | INFO     | pepbenchmark | [EPOCH 10/50] Train Loss: 0.3670, Val Loss: 1.0126
2026-03-28 11:25:17 | INFO     | pepbenchmark | [EARLY STOPPING] Stopping at epoch 10
2026-03-28 11:25:18 | INFO     | pepbenchmark | [METRICS] train: {'mse': 0.5144408795826255, 'rmse': np.float64(0.7172453412763484), 'mae': 0.5111709967405246, 'r2': 0.010920820611587612, 'pcc': np.float64(0.5410657350186414), 'spearman': np.float64(0.5405427228917141)}
2026-03-28 11:25:18 | INFO     | pepbenchmark | [METRICS] valid: {'mse': 0.8914215324913326, 'rmse': np.float64(0.9441512233171827), 'mae': 0.7170483912080741, 'r2': 0.14410193591320697, 'pcc': np.float64(0.41488335625526485), 'spearman': np.float64(0.4202660367987419)}
2026-03-28 11:25:18 | INFO     | pepbenchmark | [METRICS] test: {'mse': 0.7770307184117256, 'rmse': np.float64(0.8814934590861838), 'mae': 0.7133817761666121, 'r2': 0.07543006304732802, 'pcc': np.float64(0.31321592336224524), 'spearman': np.float64(0.3166643831443954)}
   random_seed  fold_seed   model_name  training_time  epochs_trained  \
0           42          0  gin_default      11.552020               9
1           43          1  gin_default      10.401856               8
2           44          2  gin_default      15.739025              13
3           45          3  gin_default      12.615191              11
4           46          4  gin_default      11.422501              10

   best_val_loss  train_samples  valid_samples  test_samples  train_mse  ...  \
0       0.787786           5576            697           697   0.369939  ...
1       0.814571           5576            697           697   0.454316  ...
2       0.648141           5576            697           697   0.318450  ...
3       0.917786           5576            697           697   0.406728  ...
4       0.894202           5576            697           697   0.514441  ...

   valid_mae  valid_r2  valid_pcc  valid_spearman  test_mse  test_rmse  \
0   0.733342  0.212792   0.520024        0.580641  0.862124   0.928506
1   0.746939  0.189818   0.488325        0.486594  0.900920   0.949168
2   0.642661  0.364163   0.604056        0.608305  0.669012   0.817932
3   0.751106  0.100596   0.347883        0.327279  0.887945   0.942309
4   0.717048  0.144102   0.414883        0.420266  0.777031   0.881493

   test_mae   test_r2  test_pcc  test_spearman
0  0.806684 -0.005010  0.395419       0.412789
1  0.807613 -0.077842  0.299857       0.266122
2  0.666987  0.197521  0.492930       0.496181
3  0.785457 -0.033528  0.206882       0.217145
4  0.713382  0.075430  0.313216       0.316664

[5 rows x 27 columns]
{'mean': 0.7560243543627614, 'std': 0.06292858088806504, 'min': 0.666986948448411, 'max': 0.8076126462588864}